// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Caml_string from "rescript/lib/es6/caml_string.js";

var lines = Fs.readFileSync("input.txt", "utf-8").split("\n");

function countHits(lines, dx, dy) {
  var lineLength = Belt_Array.getExn(lines, 0).length;
  return lines.reduce((function (state, line, index) {
                if (state.y !== index) {
                  return state;
                }
                var nextX = Caml_int32.mod_(state.x + dx | 0, lineLength);
                var nextY = state.y + dy | 0;
                var match = Caml_string.get(line, state.x);
                return {
                        x: nextX,
                        y: nextY,
                        hits: match !== 35 ? state.hits : state.hits + 1.0
                      };
              }), {
              x: 0,
              y: 0,
              hits: 0.0
            }).hits;
}

console.log(countHits(lines, 1, 1) * countHits(lines, 3, 1) * countHits(lines, 5, 1) * countHits(lines, 7, 1) * countHits(lines, 1, 2));

export {
  lines ,
  countHits ,
  
}
/* lines Not a pure module */
