// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_SetInt from "rescript/lib/es6/belt_SetInt.js";
import * as Caml_format from "rescript/lib/es6/caml_format.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var numbers = Belt_Array.map(Fs.readFileSync("input.txt", "utf-8").split("\n"), Caml_format.caml_int_of_string);

var numbersSet = Belt_SetInt.fromArray(numbers);

var match = numbers.find(function (n) {
      return Belt_SetInt.get(numbersSet, 2020 - n | 0) !== undefined;
    });

if (match !== undefined) {
  console.log(match, 2020 - match | 0, Math.imul(match, 2020 - match | 0));
} else {
  console.log("Not Found");
}

var match$1 = match === undefined ? undefined : Caml_option.some(match);

export {
  numbers ,
  numbersSet ,
  match$1 as match,
  
}
/* numbers Not a pure module */
